### ISSUE TITLE
Use attribute parameters for input attributes, not names.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#17]
Since these operators are effectively new, can parameters that are input attributes be of attribute type and not `String`?

E.g. https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaProducerOperator.java#L46

Should be a `TupleAttribute` not a `String`

**Comment by cancilla** [comment]
The goal with this is to ensure that the operator can accept attributes with arbitrary types. This is so that non-string keys and messages can be written to the Kafka topic.

My first attempt to support this was by using `TupleAttribute<Tuple, Object>`. This resulted in the `@Parameter` annotation complaining about unsupported attribute type. 

My second attempt was to use `TupleAttribute<Tuple, ?>`, which appears to have succeeded. I can set an attribute with an arbitrary type as a parameter value and nobody complains. 

I have updated the **KafkaProducer** operator parameters as follows: 
  * renamed `messageAttrName` to `messageAttr`
    * now accepts a tuple attribute as a value
 * renamed `keyAttrName` to `keyAttr`
    * now accepts a tuple attribute as a value
 * renamed `topicAttrName` to `topicAttr`
    * now accepts a tuple attribute as a value

**Comment by cancilla** [comment]
### NOTE
This only affects the **KafkaProducer** operator. The Java Operator API only supports specifying `TupleAttribute` as a parameter type when referring to *input attributes*. For *output attributes*, one still need to specify the name of the attribute. 

Therefore, the **KafkaConsumer** operator will have the following parameters: 
 * `outputMessageAttrName` - specifies the *name* of the output attribute
 * `outputKeyAttrName` - specifies the *name* of the output attribute
 * `outputTopicAttrName` - specifies the *name* of the output attribute

**Comment by cancilla** [comment]
The [Kafka Producer Operator Design](https://github.com/IBMStreams/streamsx.kafka/wiki/KafkaProducer-Operator-Design) has been updated to reflect the changes made here. 

Closing out this issue.

**Comment by cancilla** [comment]
I just realized that the previous Kafka operators used "messageAttribute" and "keyAttribute" as parameter names. To aide with migrating existing applications, I've updated the operator to use the same parameters.

**Comment by ddebrunner** [comment]
+1 I prefer 'Attribute', clarity is better than saving a few characters.
