### ISSUE TITLE
Problem with Consistent Cut

### ISSUE THREAD

**Issue by schulz2** [IBMStreams/streamsx.kafka#29]
While migrating code to the new Kafka toolkit I came across a problem with Consistent Cut
and the KafkaConsumer. Attached you'll find example code and the logs generated when
this code is run on my machine.

In the delivered configuration the app runs into exceptions that lead to no output data being
generated (the data that went through Kafka). When the '@consistent' annotation is commented,
the application works as expected.

[consistentRegionInKafka.zip](https://github.com/IBMStreams/streamsx.kafka/files/1115124/consistentRegionInKafka.zip)

**Comment by cancilla** [comment]
When the operator is in a consistent region, the consumer needs to store information related to the topics and partitions it will be consuming from. When the `partition` parameter is specified, the operator will only consume messages from a specific partition. However, the underlying code was attempting to retrieve and store information for all partitions for a given topic, regardless of the value specified via the `partition` parameter. 

The fix was to only retrieve and store partition information for those partitions which the consumer is actually consuming from.
