### ISSUE TITLE
Format Java code.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#5]
The Java code seems to be a mix of spaces and tabs, or at least inconsistent indentation.

Before there is too much work on it, would it be possible to have a commit that formats the code to use spaces only with 4 space indentation. E.g. Select all code in Eclipse and correct the format.

**Comment by schulz2** [comment]
Trying to avoid being "Captain Obvious" here, but as the proposed formatting of using spaces only for indentation and maybe other styles that are different to the built-in formatter profiles delivered with Eclipse: Can you provide the agreed-upon formatter profile(s) so that it may be imported into Eclipse, please?
Or is there already a web-page that defines the formats to be used?

**Comment by ddebrunner** [comment]
I think it's up to the toolkit maintainer to set a style, but a mix of tabs and spaces is not a good choice. :-)

**Comment by cancilla** [comment]
@ddebrunner  agreed...a mix of tabs and spaces is ugly. I cleaned up the code and updated the preferences in my Eclipse environment to replace tabs with spaces. I'm closing this issue.
