### ISSUE TITLE
KafkaConsumer: processTuples() error handling is incorrect.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#57]
1) At the `run()` method that invokes processTuples() any exception is caught, logged and ignored. This is incorrect, at this point any exception must cause the PE to fail, otherwise consistent region wil not work and the app will appear healthy even though it is not.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L435

2) If an `InterruptedException` is caught then it is ignored. `InterruptedException` is only used when shutdown is occurring and this should have been handled by the shutdown check at 464 (which will occur before the thread is interrupted.) Again, any unexpected exception needs to cause the operator to fail, not be ignored.

https://github.com/IBMStreams/streamsx.kafka/blob/develop/com.ibm.streamsx.kafka/impl/java/src/com/ibm/streamsx/kafka/operators/AbstractKafkaConsumerOperator.java#L488

**Comment by RolefH** [comment]
An `InterruptedException` can be thrown at two places: waiting in `resettingLatch.await()` and  `crContext.acquirePermit()`. If an InterruptedException is caught in the `produceTuples()` function, the function should be ended gracefully. This terminates the processingThread.

In addition, the shutdown() handling should be changed. Current sequence is

1. set the shutdown flag to true
1. join the processThread with timeout of 5 seconds
1. if the thread didn't join after timeout, interrupt it.

This leads to random shutdown behavior. If the processThread is waiting, for example in acquirePermit(), it can leave the wait state or not during the timeout interval - and then the thread gets  interrupted or not.

I suggest to interrupt the processThread first, and then to join it..

**Comment by ddebrunner** [comment]
With the operator api it was not intended for user code to interrupt threads, that is done automatically by the Streams runtime once the operator's `shutdown` method is complete.

It's not really clear why shutdown needs to wait for the thread at all.

**Comment by RolefH** [comment]
If the runtime interrupts and joins all threads that are created by
`getOperatorContext().getThreadFactory().newThread(...);`,
with timeout (property app.stopTimeout?) then this shutdown implementation would be sufficient:

    public synchronized void shutdown() throws Exception {
        shutdown.set(true);
        consumer.sendShutdownEvent(SHUTDOWN_TIMEOUT, SHUTDOWN_TIMEOUT_TIMEUNIT);
        OperatorContext context = getOperatorContext();
        logger.trace("Operator " + context.getName() + " shutting down in PE: " + context.getPE().getPEId() //$NON-NLS-1$ //$NON-NLS-2$
                + " in Job: " + context.getPE().getJobId()); //$NON-NLS-1$
        // Must call super.shutdown()
        super.shutdown();
    }

**Comment by RolefH** [comment]
Error handling for the eventThread seems also be wrong.
If an exception occurs in its run() method, the exception is stored in the member variable `initializationException`of the KafkaConsumerClient - and then the thread ends. No Kafka messages are read any more --> no output tuples are produced, but operator looks healthy.

Unrecoverable exceptions must be propagated to the Runtime to make the PE fail and possibly restart the PE.

**Comment by RolefH** [comment]
corrected in release v1.2.3

**Comment by anthonynassar** [comment]
This issue dealt with exceptions thrown by the Kafka Consumer presumably in the `run()` function of the `processThread` and raising afterwards a `RuntimeException` to stop the JVM and consequently stop the operator from executing.

However, when exceptions arose during the initialization phase the exception is logged without marking the operator as unhealthy. Some examples of such exceptions are `AuthenticationException`, `ConnectException` and `TimeoutException`. On the other side, `AuthorizationException` and `SerializationException` blocks the operator and therefore it shutdowns gracefully making the operator unhealthy.

As an application developer, I find it paramount to be notified through the changed state of the operator when any kind of exceptions arise. Therefore, the expected behavior is that the operator fails and stop retrying indefinitely, even for the cases where wrong credentials are provided or a connection loss to the brokers.

So, is this behavior a limitation in Kafka itself or it is expected and if not what were the motives behind this mechanism and finally is there any turnaround or a best practice to solve this issue?

**Comment by RolefH** [comment]
When the `processThread`'s `run()` catches an exception, it throws a RuntimeException, right. This will cause the PE to stop immediately and go into FAILED state when the PE is _not_ configured as restartable. Since Streams 4.0 PEs are restartable by default, however. When the PE is configured as restartable, it will go into FAILED state after 10 restart attempts when the error persists.

Failures during operator initialization will also cause PE failures and re-launches of the PE. The user _is_ notified that at least one of the operators in the PE has issues.  

To make it clear, the `processThread`s `run()` will _never_ catch Kafka related exceptions. This thread produces tuples from operator internally queued consumer records. It can catch an exception if tuple submission or tuple processing of a downstream operator fails.

Kafka related exceptions thrown by the `KafkaConsumer`'s `poll(...)` method are caught by the _event thread_ in the `AbstractKafkaConsumerClient` and handled in the same fashion except that 50 consecutive exceptions must occur before an exception is re-thrown causing the PE to fail and to re-launch.

The key is , that all uncaught exceptions thrown by threads from the OperatorContext's thread factory are handled by the Streams runtime.

FYI, I described newer implementations since late 1.x versions.

If you have an issue in your application, of which you think it is related to the Kafka operators, open an issue and provide information about toolkit version, the observed behavior, and PE trace files.
