### ISSUE TITLE
KafkaMessageConsumer - Consistent region with consumer groups?

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#72]
Is it possible today to support consistent region with consumer groups?

Ie. a collection of N KafkaMessageConsumer operators with the same group id being part of the same consistent region. Regardless of any failure messages are processed at least once.

If not could such a combination be supported?

**Comment by RolefH** [comment]
Consistent Region and consumer groups exclude each other. In a consumer group, Kafka's group coordinator assigns the partitions to the consumers of the same group in such a way, that no partition of a topic is consumed by more than one consumer within the group. If number of partitions > number of consumers, consumers remain idle. The group coordinator can decide to change the assignment of partitions to consumers, however. For the consistent region reset, this means, that the assignment must be reverted back if it changed. Otherwise the offset reset and tuple replay can not be done correctly. Thats why, the KafkaConsumer always assigns to one or all topic partition(s) when it is in a CR.

The groupId (app config, property, or a parameter in future release) has no effect in terms of Kafkas group coordination feature when the KafkaConsumer is in a CR or if a specific partition to consume from is specified. This one I wanted to document more clearly.

Together with CR It is only possible to statically assign each consumer to one single topic partition, but then no failover to another consumer will happen if one of them dies or gets disconnected (for longer than the heartbeat timeout).

* Is it really desired to have a failover in a CR scenario?
* I can imagine, that it would be desirable to have dynamic load sharing in a CR with N consumers consuming M topic partitions; M >= N
* I can also imagine, that it would be nice to automatically assign a consumer to an administratively added partition within a load sharing scenario, what a static assignment of a partition can't do.

I have to think about what it means for the checkpoint and reset function if we want to support such a combination. The checkpoint taken on `checkpoint` contains the offset of last submitted tuple+1 for each topic partition. On `reset`,  these offsets would be the start offsets to read from. For the reset, this implies that a Consumer is still assigned to the same topic partitions as at checkpoint time. This is not guaranteed if the group coordinator can change the assignment of partitions to consumers theoretically at any time.

**Comment by RolefH** [comment]
Consistent Region relies on ability to seek to offsets. An offset is always an offset within a _partition_, so that an operator instance within a consistent region is always statically associated to one ore more topic partitions. That's why Kafka's group management feature and CR exclude each other.

The groupId config has only effect in such cases, where the consumer does not need to seek to a specific position (offset, time, begin).

**Comment by ddebrunner** [comment]
What I wondered about is when kafka reassigns a partition what does it use as the starting offset for the new consumer?

Is there some acknowledge protocol we could use that would tie in with consistent region?

Even without consistent region we have unprocessed messages in the operator's message queue that are lost on a failure, there must be some acknowledge protocol kafka provides to allow those to be reread by other consumers.

**Comment by RolefH** [comment]
#### These will be the changes in the user interface of the KafkaConsumer operator:
- new operator parameter **consistentRegionAssignmentMode** with possible values `Static` and `GroupCoordinated`.
    - `Static` is the default and is the current behavior in consistent region: The operator statically assigns itself to the given topic partitions (**partition** parameter) or to all partitions gathered at initialization time from the topic's metadata. This mode guarantees that each consumer operator keeps assigned to the topic partitions on consistent region reset. Kafka's group management feature is disabled.
    - `GroupCoordinated` enables Kafka's group management in a consistent region. This mode guarantees that the _consumer group_ replays tuples after CR reset. Partition assignments can change. Application developers must keep this in mind when developing applications. This mode is incompatible with the the operator parameters **partition** and **startOffset**, and with the **startPosition** parameter value `Offset`, which requires these parameters. This mode is also incompatible with the control port function that allows adding and removing topic partitions to be consumed. These features require assignment of partitions by the operator.
- When `GroupCoordinated` is used for **consistentRegionAssignmentMode**, all consumer operators must be in one consistent region - this will be verified at initialization time. UDP with independent parallel operator chains results in independent consistent regions for each parallel channel. Such applications are not supported with `GroupCoordinated`.
- the **triggerCount** parameter is used for operator driven CR. Multiple operator driven initiators that would belong to one consumer group are not supported in one CR. This parameter can only be used if the consumer group contains exactly one consumer operator, which is not the typical scaling use case. The consumer would automatically detect adminstrative changes of partitions, however.

**Comment by RolefH** [comment]
Tasks
- [ ] SPL doc update regarding operator behavior in Consistent Region (operator description)
- [ ] SPL doc update for parameters and dependencies
- [x] SPL sample
- [ ] functional description - in github.io, Link to the SPL doc

**Comment by RolefH** [comment]
The parameter **consistentRegionAssignmentMode** mentioned in two comments above should be renamed to **assignmentMode** or simply to **enableGroupManagement** (true|false). Such a naming makes the parameter usable also when not in consistent region.. When not in consistent region, static assignment stabilizes applications that do not need group management, for example, application with only one consumer operator.

When not in consistent region, static assignment happens today only when the **partition** parameter is used, or when **startPosition** != `default`. Once issue #94 (*KafkaConsumer does not allow group management with startPosition BEGINNING, END, or TIME*) is implemented, for static assignment the partition(s) must be specified via **partition** parameter.

**Comment by ddebrunner** [comment]
Just curious if a new parameter is needed. The 1.4 version KafkaConsumer already has options to set it in group management mode, why the need to an additional parameter?

**Comment by RolefH** [comment]
@ddebrunner 
group management mode should be the default. It should be default for both, consistent region, and when not in CR. (This means, that we change the default behaviour for CR, but I believe that CR is not widely used with Kafka or MH toolkit, and therefore it's not a problem, when it is documented in the release notes and SPL doc). When I implement issue #94 *(KafkaConsumer does not allow group management with startPosition BEGINNING, END, or TIME)*, there is no option **NOT** to involve the group coordinator when not in CR. Group coordination then will always be enabled, except when the operator is pinned to partitions with **partition** parameter. But then the user must have prior knowledge about the partitions of the topics. I don't like 'special' parameter values to enforce a specific behaviour, like `partition: -1;` to make the operator assign statically to *all* partitions. I would prefer one parameter that enables group management or not. When in CR, this parameter is now **consistentRegionAssignmentMode**, which is nothing else than *enableGroupManagement* (true|false) for CR.

**Why do I want to give the user the option NOT to involve the group coordinator?**
 I have seen several projects, which use a single MH consumer without being in a CR. Users do not care about balancing partitions, they do not care about downstream congestion, which make the consumer stop polling for an unpredictable period of time > `max.poll.interval.ms`, they all suffer being kicked out of the group, re-joining the group because they do not care about tweeking the group management related timers. These users would go best with static partition assignment without the need to specify all the partitions via a parameter. The only disadvantage they would have, that they must restart the application when partitions are added by a topic administrator.

But perhaps the problematic behaviour on downstream congestion goes away with the recent changes I made for the case that the message queue has no space (queue full or lack of memory): pause fetching but continue polling to show aliveness of the consumer. Resume fetching when there is space again.

Anyway, what I want to do very soon, is to change the default value of the new **consistentRegionAssignmentMode** parameter from `Static` to `GroupCoordinated`.

**Comment by ddebrunner** [comment]
@RolefH I think this goes to the issue of we need to describe the user scenarios we are trying to support. And then figure out how to parameterize the operator. I think we seem to be doing it the other way around, define the parameters and then what the user wants to achieve. Somewhat due to the parameters already existing.

However I don't get what the eventual plan is, is it to have a parameter of:
  * `consistentRegionAssignmentMode`
  * `assignmentMode`
  * No parameter for assignment mode, group management is the default and always set unless partitions are explicitly assigned using `partition`?

**Comment by ddebrunner** [comment]
Maybe it's time to think about a 2.0 release that breaks compatibility and simplifies the operators?

My gut feel is that 99% of apps will just be subscribing to a single topic and 95% of those will use group coordination, 5% using partition assignment (most likely 1-1). The control port and multiple topics is just complications few care about.

In exposing the toolkit for Python (`streamsx.messagehub`) I won't be exposing multiple topics or control ports, just two or three modes, based upon user scenarios. Streams Designer will take a similar approach.

Another possible approach is to leave the core `MessageHub/KafkaConsumer` as-is but add new SPL composite operators that support the typical single topic case(s) cleanly.

**Comment by RolefH** [comment]
@ddebrunner 
current plan is:
- `consistentRegionAssignmentMode` is the name of the parameter - ignored when not in CR
- its default value is `GroupCoordinated`
    - different from 1.5.0 alpha release and all alpha tagged versions; I want to have same default behaviour related to group management when in CR and when not in CR
    - behavioural change when consumer is in CR and SPL application is not adapted.
    - default behaviour related to group management must not be different when in CR and when not in CR.
- no parameter for assignment mode when not in CR
- After implementation of #94, group management is always enabled unless **partition** parameter is used
    - yet another behavioural change for **startPosition**: `{Begin|End|Time}`

Now in version v1.4.2, and v1.5.0, group management is only enabled when **startPosition** = `Default` and **partition** parameter is not used. For use outside CR, the user is more restricted than in CR.

**Comment by RolefH** [comment]
@ddebrunner 
Multiple topics is not the issue. The default values must match the 95% uses.
- I know that the control port is used
- startPosition is used by us for testing with pre-filled topics

**Comment by ddebrunner** [comment]
@RolefH Sorry, still confused, these statements seem to be contradictory:

> consistentRegionAssignmentMode is the name of the parameter 
> After implementation of #94, group management is always enabled unless partition parameter is used

So there will be two different mechanisms to define the state of using group management?

**Comment by ddebrunner** [comment]
> I know that the control port is used
I didn't say it wouldn't be used, I said that most applications will not use it.

> startPosition is used by us for testing with pre-filled topics
Testing by the developers of the operator is a special case, not the standard use cases by applications.

**Comment by RolefH** [comment]
> @RolefH Sorry, still confused, these statements seem to be contradictory:
> 
> > consistentRegionAssignmentMode is the name of the parameter
> > After implementation of #94, group management is always enabled unless partition parameter is used
> 
> So there will be two different mechanisms to define the state of using group management?

@ddebrunner 
Another proposal, perhaps the most intuitive:
- No operator parameter at all to define state of group management - no **consistentRegionAssignmentMode** parameter
- when group ID is specified, group management takes place unless control port or **partition** parameter is used
- when no group ID is specified, consumers are assigned manually to partitions (given partitions or all)

**Comment by RolefH** [comment]
> Another proposal, perhaps the most intuitive:
> 
>  * No operator parameter at all to define state of group management - no **consistentRegionAssignmentMode** parameter
> 
>  * when group ID is specified, group management takes place unless control port or **partition** parameter is used
> 
>  * when no group ID is specified, consumers are assigned manually to partitions (given partitions or all)

Targeted for the 1.5.0.beta1 release of Kafka and Message Hub toolkit.

**Comment by RolefH** [comment]
closed with release [v1.5.0](https://github.com/IBMStreams/streamsx.kafka/releases/tag/v1.5.0)
