### ISSUE TITLE
kafkaProducer consistent region strategy documentation is incorrect.

### ISSUE THREAD

**Issue by ddebrunner** [IBMStreams/streamsx.kafka#77]
The intro says: _'at least once' (default behavior) and 'exactly once' delivery semantics._

Exactly once is not supported, if the consistent region fails after the checkpoint that committed the transaction then the region will reset and then likely messages will be resbmitted to the topic by the producer.

The region can fail after checkpoint if other operators hit a problem checkpointing after the producer has completed, e.g. other sink operators including other producers, say if the producer is in a UDP region.

Transactional gives at least once with less chance of duplication for external consumers  with `isolation.level = read_committed`.

**Comment by ddebrunner** [comment]
Should the quotes around the term _at least once_, be removed?
Just use italics from a term, e.g.

_at least once_ delivery semantics.

Maybe it's just my English background with heavy use of sarcasm, but it reads as though air-quotes are being placed around the terms , as in it's almost at least once. :-)

**Comment by RolefH** [comment]
*Exactly once delivery*, new SPL doc:

Messages are always inserted into a topic within the context of a transaction. Transactions are committed when the operator checkpoints. If the operator crashes or is reset while in a consistent region, the operator will abort the ongoing transaction and write all tuples replayed within a new transaction. External consumers configured with `isolation.level=read_committed` will not read the duplicates from the aborted transactions. Consumers that use a different isolation level will read duplicate messages similar to *at least once* delivery.

To ensure that replayed tuples are not committed multiple times when the consistent region fails between commit and the point when the entire region has reached a consistent state, the operator writes the current checkpoint sequence number as commit-ID together with its unique *transactional ID* into the control topic **__streams_control_topic** as part of the committed transaction. The checkpoint sequence number is part of the operator's checkpointed state and represents the last successfully committed ID.

When the consistent region fails after commit, the last successfully committed ID is reset to the previous value and tuples are replayed. When the operator checkpoints next time, it detects the difference between the committed ID within the control topic and the restored ID from the checkpoint data and aborts the Kafka transaction rather than committing the replayed data again.

**NOTE 1:** Transactions in Kafka have an inactivity timeout with default value of 60 seconds. If the consistent region triggers less frequently and you expect a low message rate, consider to to increase the timeout by setting the producer property `transaction.timeout.ms` to a higher value, for example 120000 (milliseconds). The maximum value of this property is limited by the server property `transaction.max.timeout.ms`, which has a default value of 900000.

**NOTE 2:** In Kafka environments that have disabled automatic topic creation (broker config `auto.create.topics.enable=false`), the control topic with the name **__streams_control_topic** must be created manually before **consistentRegionPolicy** can be used with `Transactional`.

**NOTE 3**: For exactly once delivery semantics, the Kafka broker must have version 0.11 or higher because older brokers do not support transactions.


**General remark for Exactly Once Applications**
For exactly once, an application must be deterministic, so that replayed data produces exactly the same output data at all ends of the consistent region. This forbids non-deterministic features like time-based windows, some fan-in and fan-out scenarios.

**Comment by RolefH** [comment]
fixed in release v1.3.1
